services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=logistics-santander'
      - 'POSTGRES_PASSWORD=santander'
      - 'POSTGRES_USER=santander'
    ports:
      - '5432:5432'
