services:
  app:
    image: 'eclipse-temurin:21-jdk'
    container_name: santander
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .src:/app/src
    ports:
      - '8080:8080'
    restart: on-failure
    networks:
      - app-santander
    environment:
      - 'POSTGRES_PASSWORD=santander'
      - 'POSTGRES_USER=santander'
    depends_on:
      - postgres
      - wiremock

  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=logistics-santander'
      - 'POSTGRES_PASSWORD=santander'
      - 'POSTGRES_USER=santander'
    ports:
      - '5432:5432'
    networks:
      -  app-santander
  wiremock:
    image: 'wiremock/wiremock:latest'
    container_name: wiremock_shipping
    ports:
      - "8081:8080"
    volumes:
      - ./wiremock:/home/wiremock
    networks:
      - app-santander

networks:
  app-santander:
    driver: bridge
