spring:
  application:
    name: santander
  datasource:
    url: jdbc:postgresql://postgres:5432/logistics-santander
    username: santander
    password: santander
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: false


google:
  maps:
    key: ${GOOGLE_MAPS_KEY}

#springdoc:
#  swagger-ui:
#    url: /openapi/openapi.yaml
#    enabled: true
#    path: /swagger-ui.html
#    version: 1.0.0
#    display-request-duration: true
#    groups-order: desc
#    operations-sorter: method
#    disable-swagger-default-url: true
#    use-root-path: true
#  api-docs:
#    version: openapi_3_1
#    path: /api-docs
#  show-actuator: true
#  group-configs:
#    - group: shipping
#      paths-to-match:
#        - /shipping/**
#  cache:
#    disabled: true
#  use-management-port: true

server:
  port: 8080

