spring:
  application:
    name: santander
  datasource:
    url: jdbc:postgres://${BD_HOST}:${BD_PORT}/logistics-santander
    username: ${BD_USERNAME}
    password: ${BD_PASSWORD}
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
        alphanumeric-ids:
          enabled: true

google:
  maps:
    key: ${GOOGLE_MAPS_KEY}

