spring:
  application:
    name: santander
  datasource:
    url: jdbc:postgres://localhost:5432/logistics-santander
    username: santander
    password: santander
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
        alphanumeric-ids:
          enabled: true

